# -*- coding: utf-8 -*-
"""2.1 - Olá [nome em maiúsculo]

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MTXF8VV9t9Z9ImwVPzBZvgLOfH5zmX3D
"""

nome = input("")
print("Olá "+nome.upper())