# -*- coding: utf-8 -*-
"""2.2 - Contar frequência

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16dXTXY_sZxQM-dBaJ1gkawXHs7DJsTIQ
"""

str1 = input("")
str2 = input("")

print(str1.count(str2))