# -*- coding: utf-8 -*-
"""2.3 - Contar frequência (insensível à caixa)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1np3pDQjFWnfKI-YTskgIg7Ss4ixJ-JZm
"""

str1 = input("").upper()
str2 = input("").upper()

print(str1.count(str2))