# -*- coding: utf-8 -*-
"""2.4 - Trocar palavra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vuon16zBnsyiWKk4JpwCiWVXntaoOPOE
"""

str1 = input("")
str2 = input("")
str3 = input("")

replace = str1.replace(str2, str3)

print(replace)