# -*- coding: utf-8 -*-
"""2.5 - Grau para radiano

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H21zYqtg0dsp09yKzd5Lw_FBgucfsvxt
"""

import math

graus = float(input(""))
radianos = math.radians(graus)
print("{:.2f}".format(graus)+" graus correspondem a "+"{:.2f}".format(radianos)+" radianos.")