# -*- coding: utf-8 -*-
"""2.6 - Metros para pés e polegadas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14D1NI_4nEa9FUGkQIMZwWMGCO69IK2ML
"""

import math

cm = float(input(""))

m = cm / 100
cm_pol = cm / 2.54
pol_pe = cm_pol / 12

pe = math.floor(pol_pe)
pol = math.ceil(cm_pol % 12)

print("{:.2f}".format(m)+" metros correspondem a "+str(pe)+" pés e "+str(pol)+" polegadas.")