# -*- coding: utf-8 -*-
"""2.7 - Hora:Minuto:Segundo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uzWMKuskSNQ2cV66uLymqXlyrA8nzuBU
"""

ts = int(input(""))

h = ts // 3600
m = (ts % 3600) // 60
s = (ts % 3600) % 60

print(str(ts)+" segundos correspondem "+str(h)+":"+"{:02d}".format(m)+":"+"{:02d}".format(s)+".")
